
            (define (problem lightsoutproblem)
                (:domain lightsout)
                (:objects x0 x1 x2 x3 x4 - linha y0 y1 y2 y3 y4 - coluna)
                (:init
                    (ta-ligada x0 y2)
(ta-ligada x0 y3)
(ta-ligada x0 y4)
(ta-quebrada x1 y2)
(ta-ligada x1 y3)
(ta-ligada x1 y4)
(ta-ligada x2 y0)
(ta-quebrada x2 y1)
(ta-ligada x2 y3)
(ta-quebrada x2 y4) (ta-ligada x2 y4)
(ta-ligada x3 y0)
(ta-ligada x3 y1)
(ta-quebrada x3 y2)
(ta-ligada x3 y3)
(ta-quebrada x4 y0) (ta-ligada x4 y0)
(ta-ligada x4 y4)
(inc x0 x1)
(inc x1 x0)
(inc x1 x2)
(inc x2 x1)
(inc x2 x3)
(inc x3 x2)
(inc x3 x4)
(inc x4 x3)
(inc y0 y1)
(inc y1 y0)
(inc y1 y2)
(inc y2 y1)
(inc y2 y3)
(inc y3 y2)
(inc y3 y4)
(inc y4 y3)
                )
                (:goal
                    (and
                        (not (ta-ligada x0 y0))
(not (ta-ligada x0 y1))
(not (ta-ligada x0 y2))
(not (ta-ligada x0 y3))
(not (ta-ligada x0 y4))
(not (ta-ligada x1 y0))
(not (ta-ligada x1 y1))
(not (ta-ligada x1 y2))
(not (ta-ligada x1 y3))
(not (ta-ligada x1 y4))
(not (ta-ligada x2 y0))
(not (ta-ligada x2 y1))
(not (ta-ligada x2 y2))
(not (ta-ligada x2 y3))
(not (ta-ligada x2 y4))
(not (ta-ligada x3 y0))
(not (ta-ligada x3 y1))
(not (ta-ligada x3 y2))
(not (ta-ligada x3 y3))
(not (ta-ligada x3 y4))
(not (ta-ligada x4 y0))
(not (ta-ligada x4 y1))
(not (ta-ligada x4 y2))
(not (ta-ligada x4 y3))
(not (ta-ligada x4 y4))
                    )
                )
            )
            